# -*- coding: utf-8 -*-
"""Dog_vs_Cat_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MLidxoApaXNKr5qkr-1wLgeg5HnS-Tw
"""

!pip install tensorflow_datasets

import tensorflow as tf
import tensorflow_datasets as tfds
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset, info = tfds.load('cats_vs_dogs', with_info=True, as_supervised=True)

class_names = info.features['label'].names
class_names

for i, example in enumerate(dataset['train']):
  image,label = example
  save_dir = './cats_vs_dogs/train/{}'.format(class_names[label])
  os.makedirs(save_dir, exist_ok=True)

  filename = save_dir + "/" + "{}_{}.jpg".format(class_names[label],i)
  tf.keras.preprocessing.image.save_img(filename, image.numpy())

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization

datagen = ImageDataGenerator(rescale=1/255, validation_split=0.2, rotation_range=10, width_shift_range=0.1, height_shift_range=0.1, shear_range=0.1, zoom_range=0.10, horizontal_flip=True)

train_generator = datagen.flow_from_directory('/content/cats_vs_dogs/train',
                                              target_size = (150,150),
                                              batch_size=128,
                                              class_mode='binary',
                                              subset='training')

validation_generator = datagen.flow_from_directory('/content/cats_vs_dogs/train',
                                              target_size = (150,150),
                                              batch_size=128,
                                              class_mode='binary',
                                              subset='validation')

model = Sequential()
#1st layer CNN
model.add(Conv2D(32, kernel_size=3, activation='relu', input_shape=(150, 150, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

#2nd layer CNN
model.add(Conv2D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

#3rd layer CNN
model.add(Conv2D(128, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(512, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.summary()

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

history=model.fit(train_generator, epochs=10, validation_data=validation_generator)

history.history

plt.plot(history.history['accuracy'], label='Training')
plt.plot(history.history['val_accuracy'],label='Validation')
plt.legend(['Training', 'validation'])
plt.show()

model.save('cats_vs_dogs.h5')

model_load= tf.keras.models.load_model('cats_vs_dogs.h5')

import requests
from PIL import Image
import numpy as np
from tensorflow.keras.preprocessing import image
from IPython.display import display

img_url = "https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg"
img = Image.open(requests.get(img_url, stream=True).raw).resize((150,150))

display(img)

image_array = image.img_to_array(img)

img = np.expand_dims(image_array, axis=0)

img = img/255

prediction = model.predict(img)
print(prediction)

TH = 0.5
prediction = int(prediction[0][0]>TH)
classes = {v:k for k,v in train_generator.class_indices.items()}
classes[prediction]
